name: Bonjour
on:
  - push

jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "mynode"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker image build --tag="${IMAGE_NAME}" ./

      - name: Run lint
        run: docker container run "${IMAGE_NAME}" npm run lint

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "ruddymo"
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          push: true
          context: "./"
          tags: ruddymo/sayhello:${{ github.ref_name }}

      - name: Build and push if Unstable
        uses: docker/build-push-action@v6
        if: contains('refs/heads/main', github.ref)
        with:
          push: true
          context: "./"
          tags: ruddymo/sayhello:unstable
